### ISSUE TITLE
Extension key missing in composer.json

### ISSUE THREAD

**Issue by seirerman** [AOEpeople/TYPO3-Cache-Management#11]
Composer says:
`The TYPO3 extension package "aoepeople/cachemgm", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)
`
There's also a check in the reports module with a complaint, and the module even suggests an updated version of composer.json.

```
{
    ...
    "extra": {
        "branch-alias": {
            "dev-master": "10.0.0-dev"
        },
        "typo3/cms": {
            "cms-package-dir": "{$vendor-dir}/typo3/cms",
            "web-dir": ".Build/Web",
            "extension-key": "cachemgm"
        }
    }
}
```

It's only a very minor issue and easily fixable. The extension works fine without the extension key (so far).

**Comment by TomSchenk** [comment]
resolved by 1aaea21786aad330185eb842705f01b5fa5910b4
