### ISSUE TITLE
Support for TYPO3 8.7

### ISSUE THREAD

**Issue by fnagel** [AOEpeople/TYPO3-Cache-Management#2]
Please add support for TYPO3 8.7. Some basic tests seems to work as expected.

**Comment by tomasnorre** [comment]
Can you please test the latest release 3.2.2

Is from my tests compatible.

**Comment by tomasnorre** [comment]
I released version 4.0.0 which is for sure compatible with version 8.7 LTS. 

https://packagist.org/packages/aoepeople/cachemgm
